### ISSUE TITLE
Training the BDD100K dataset issue

### ISSUE THREAD

**Issue by HT24TH** [datvuthanh/HybridNets#108]
Hi, I'm trying to train the bdd100k dataset by running the command ''python train.py -p bdd100k''. The training process begins, but after reaching 40%, the computer gets stuck and screen turns black.
Does anyone has suggestions on how to solve that??
Thanks in advance.

**Comment by dn3305** [comment]
You will need at least 48GB of RAM for this. when i had 16GB, it would go blank after an hour or two. After 48 GB, the model trains till around 20k images with 73.7% accuracy, that too pc crashed but checkpoints saved the last one, which was hybridnets70000.pth

**Comment by HT24TH** [comment]
Thank you, I solved that by training the data in GPU.
the last saved weight for me is 35000 (I used 500 epochs), obtained acc=70.7%.
