### ISSUE TITLE
Drivable and Lane Type training 

### ISSUE THREAD

**Issue by abhigoku10** [datvuthanh/HybridNets#21]
@datvuthanh  thanks for sharing the code based i have following queries 
1. since bdd100k has different types of lanes eg double yellow, single white lane , dashed, can we use current source code to train for different lane types? is so what are the modifications need to be made int he code based 
2. Can we similar train the current source code with the driveable area and alternate drivable area labels ? if so what are the changes to be made 

Please share your thoughts 
Thanks in advance

**Comment by datvuthanh** [comment]
Yes, I don't think it is problem. On segmentation task, the imbalanced classes is a challenge and we solved this problem by combining between Focal Loss and Tversky Loss. You can try it and adjust parameters a, b:
``` Loss = a * Focal Loss + b * Tversky Loss ```

**Comment by xoiga123** [comment]
> Yes, I don't think it is problem. On segmentation task, the imbalanced classes is a challenge and we solved this problem by combining between Focal Loss and Tversky Loss. You can try it and adjust parameters a, b: `Loss = a * Focal Loss + b * Tversky Loss`

I think he's correct 👍
Linking to #20 for easy tracking.
