### ISSUE TITLE
Training log?

### ISSUE THREAD

**Issue by viet24dung** [datvuthanh/HybridNets#24]
Hello
I want to retrain your model. 
Could u provide a training log file?
thanks very much

**Comment by xoiga123** [comment]
Sorry, logs are unavailable. We did lots of backtracking through different checkpoints to experiment, and logging quickly went FUBAR. Please follow our (training stages guideline)[https://github.com/datvuthanh/HybridNets#training-stages] and hope for the best. Feel free to update your results in this thread and we'll be here to assist. Good luck!
