### ISSUE TITLE
light weight backbone

### ISSUE THREAD

**Issue by ForestWang** [datvuthanh/HybridNets#25]
would you support some light weight backbones such as RepVGG which is GPU friendly?

**Comment by xoiga123** [comment]
Sure thing! We hid it inside `backbone.py` but now we're bringing it to light (command-line). Use [timm](https://github.com/rwightman/pytorch-image-models) to replace your backbone. Try

`python train.py -p bdd100k -bb repvgg_b0`

This is basically what we do under the hood:

```python
if backbone_name:
            self.encoder = timm.create_model(backbone_name, pretrained=True, features_only=True, out_indices=(2,3,4))  # P3,P4,P5
```

**Comment by MartinPR307** [comment]
Hello, after switching to repvgg_b0, the following error occurs：
![image](https://github.com/datvuthanh/HybridNets/assets/42261858/a05493f8-9906-4d53-96eb-8d5bcd477b26)

**Comment by MartinPR307** [comment]
@datvuthanh @xoiga123

**Comment by MartinPR307** [comment]
@ForestWang Have you encountered the same problem?

**Comment by HT24TH** [comment]
I have the same problem @MartinPR307, any suggestion to solve that @datvuthanh @xoiga123.
Thank you.

**Comment by Masternagi** [comment]
> 您好，切换到 repvgg_b0 后，出现以下错误： ![image](https://github.com/datvuthanh/HybridNets/assets/42261858/a05493f8-9906-4d53-96eb-8d5bcd477b26)

@xoiga123
