### ISSUE TITLE
Could not use Pytorch quantization for model

### ISSUE THREAD

**Issue by tiendatAI** [datvuthanh/HybridNets#27]
`model_to_quantize = copy.deepcopy(model)`

`qconfig_dict = {"": torch.quantization.get_default_qconfig('qnnpack')}`

`model_to_quantize.eval()`

`# prepare`
`model_prepared = quantize_fx.prepare_fx(model_to_quantize, qconfig_dict)`

`# calibrate (not shown)`
`# quantize`
`model_quantized = quantize_fx.convert_fx(model_prepared)`

When using Pytorch quantization [example](https://pytorch.org/tutorials/prototype/fx_graph_mode_quant_guide.html) for your model, I get this following error: 
>~/Documents/DL_course_project/HybridNets/backbone.py in forward(self, inputs)
    100 
    101         # p1, p2, p3, p4, p5 = self.backbone_net(inputs)
    102 -->        p2, p3, p4, p5 = self.encoder(inputs)[-4:]  # self.backbone_net(inputs)
    103 
    104         features = (p3, p4, p5)
>NameError: module is not installed as a submodule

How can I avoid this error?

**Comment by xoiga123** [comment]
Hi, we currently do not have much experience in Pytorch quantizating. Seems like you need to modify the model to be _symbolically traceable_. You can skip the non-traceable parts using this [guide](https://pytorch.org/tutorials/prototype/fx_graph_mode_quant_guide.html) for the time being, or try eager mode quantization. Keep us updated with your progress, we're learning too.

**Comment by xoiga123** [comment]
@tiendatAI how's it been? It's not like we are in dire need of a quantizated model right now or anything, but it would be cool if you can share your results with us :wink:
