### ISSUE TITLE
a problem in training?

### ISSUE THREAD

**Issue by huoguangdiandian** [datvuthanh/HybridNets#30]
您好，我在训练完一个epoch，做val的时候训练程序被杀死，没有任何其他报错，请问是什么原因啊？
![1653270926(1)](https://user-images.githubusercontent.com/45250079/169728927-b47379d7-ae9e-470e-8edc-1b576bb763d7.jpg)

**Comment by datvuthanh** [comment]
Sorry @huoguangdiandian, we dont understand what you said. We are Vietnamese not Chinese. 

Thank you

**Comment by huoguangdiandian** [comment]
> Sorry @huoguangdiandian, we dont understand what you said. We are Vietnamese not Chinese.
> 
> Thank you

i am sorry@datvuthanh, The meaning of this problem is that when I started to execute val function after training an epoch, the program was directly killed without any error reported. However, I reduced the verification set to 1000 pieces and could train normally, but there was still a problem with the verification, and the verification result could not be obtained, and loss was invalid
![image](https://user-images.githubusercontent.com/45250079/169935370-ac89ac9a-1f68-4f27-b7c0-0b9b29af21db.png)

**Comment by datvuthanh** [comment]
Hi @huoguangdiandian , because we set nms iou threshold (line 61 in val) is 0.0001 to get largest recall. You can turn off val during training or modifying up to 0.5.

**Comment by datvuthanh** [comment]
But I see your validation data is Nan, so you should check your data again.

**Comment by huoguangdiandian** [comment]
> But I see your validation data is Nan, so you should check your data again.

thanks, I'll try again with your suggestion

**Comment by aimuch** [comment]
I meet the same issue:
OS: Ubuntu20.04
GPU: 3090
CUDA: 11.3
```shell
checkpoint...
Step: 4374. Epoch: 0/100. Iteration: 4375/4375. Cls loss: 0.60701. Reg loss: 6.50388. Seg loss: 0.52209. Total loss: 7.63298: 100%|#|
100%|###############################################################################################| 625/625 [18:14<00:00,  1.75s/it]
Val. Epoch: 0/100. Classification loss: 5.52566. Regression loss: 7.34373. Segmentation loss: 0.54545. Total loss: 13.41485
[1]    2482 killed     python train.py -p bdd100k -c 3 -n 8 -b 16 --freeze_seg True -v True  100
```

**Comment by xoiga123** [comment]
@aimuch Sorry to hear that, please check [this comment](https://github.com/datvuthanh/HybridNets/issues/16#issuecomment-1095370241) for workarounds. I'll put this in the readme so people know about it.

**Comment by aimuch** [comment]
> @aimuch Sorry to hear that, please check [this comment](https://github.com/datvuthanh/HybridNets/issues/16#issuecomment-1095370241) for workarounds. I'll put this in the readme so people know about it.

Think you, I will try later.

**Comment by aimuch** [comment]
> @aimuch Sorry to hear that, please check [this comment](https://github.com/datvuthanh/HybridNets/issues/16#issuecomment-1095370241) for workarounds. I'll put this in the readme so people know about it.

There is another error:
<img width="877" alt="Snipaste_2022-06-24_22-40-27" src="https://user-images.githubusercontent.com/17581911/175569315-d8c3f1f3-f430-4e73-a351-552626c87350.png">

After the code is modified to the following, it can be trained normally：
<img width="944" alt="Snipaste_2022-06-24_23-35-03" src="https://user-images.githubusercontent.com/17581911/175569419-e21614c0-f10c-4c5d-a0af-a8bae29b5b16.png">

**Comment by yaoshanliang** [comment]
Same error. The program will be killed when validating.

And the validating process is so slow, do I need to change some configs when doing validating?
