### ISSUE TITLE
How to prepare the bdd100k dataset?

### ISSUE THREAD

**Issue by yt7589** [datvuthanh/HybridNets#37]
Hi.
According to the README.txt, I had prepared bdd100k dataset. But the BddDataset failed to load the dataset. I think something wrong with my bdd100k dataset preparation process. In fact I had no idea about where to put colormaps, masks, polygons, rles folder of drivable and lane. I don't know where to put the json file of detection labels. 

Please give the detailed folder structure.

**Comment by xoiga123** [comment]
We have a [colab notebook](https://colab.research.google.com/drive/1dpMrjgJs3qKxaKR833RJDyZTh2O1-Wyn?usp=sharing#forceEdit=true&sandboxMode=true) for that.
