### ISSUE TITLE
Train flow

### ISSUE THREAD

**Issue by aimuch** [datvuthanh/HybridNets#43]
hello，
In the [### Training stages](https://github.com/datvuthanh/HybridNets/blob/8fd2490766796049df7b639e727b46280b8526e9/README.md?plain=1#L253)  
Are these three steps independent? My understanding is that the second step needs to continue training on the model of the first step, the third step continues to train on the model of the second step, and the second and third steps are specified by -w.
Right?

Thank you

**Comment by xoiga123** [comment]
@aimuch yes that's correct
