### ISSUE TITLE
Out of memory error during call val.py?

### ISSUE THREAD

**Issue by yt7589** [datvuthanh/HybridNets#44]
In the training phase when it calls val.py to evaluate the model performance it will suspend for about half an hour and then display killed. Use the command:
```
dmesg | egrep -i -B100 "killed process"
```
It would report that the python process was killed because out of memory error occured.

How to solve this problem?

**Comment by xoiga123** [comment]
@yt7589 please check [this section](https://github.com/datvuthanh/HybridNets#3-evaluate).
