### ISSUE TITLE
How to select  number of gpus?

### ISSUE THREAD

**Issue by qiumeng6** [datvuthanh/HybridNets#51]
hi, 
i want to train on multiple gpus with train_DDP.py,
but i do not know which param determine the number of gpus.
Looking forward to your reply ！ Thank you!

**Comment by xoiga123** [comment]
Hi, you can use `python3 train_ddp.py --num_gpus 8`

**Comment by happyday-lkj** [comment]
> Hi, you can use `python3 train_ddp.py --num_gpus 8`

which code branch did you use?
