### ISSUE TITLE
dataset link in colab doesnt work

### ISSUE THREAD

**Issue by zehranrgi** [datvuthanh/HybridNets#76]
Hi, 

This link is required access permission. Could you help with it? 
https://drive.google.com/drive/folders/1iW9Darrars4xc9uHq2ZnRsWoJolCcyzg?usp=sharing

**Comment by SungjinDavidLee** [comment]
Same problem from my side as well.

**Comment by zehranrgi** [comment]
https://github.com/hustvl/YOLOP 

There are also dataset links. I think it is the same...

**Comment by zehranrgi** [comment]
Download the annotations of detection from [det_annotations](https://drive.google.com/file/d/1Ge-R8NTxG1eqd4zbryFo-1Uonuh0Nxyl/view?usp=sharing).

Download the annotations of drivable area segmentation from [da_seg_annotations](https://drive.google.com/file/d/1xy_DhUZRHR8yrZG3OwTQAHhYTnXn7URv/view?usp=sharing).

Download the annotations of lane line segmentation from [ll_seg_annotations](https://drive.google.com/file/d/1lDNTPIQj_YLNZVkksKM25CvCHuquJ8AP/view?usp=sharing).https://drive.google.com/file/d/1Ge-R8NTxG1eqd4zbryFo-1Uonuh0Nxyl/view

**Comment by datvuthanh** [comment]
Yes, it is the same. Thank you, I will update it soon.

**Comment by holestine** [comment]
The links on the main page still are not working.
