### ISSUE TITLE
Hybridnets_test_video.py produces no result

### ISSUE THREAD

**Issue by jsaffyvtti** [datvuthanh/HybridNets#79]
After running: python hybridnets_test_videos.py -w weights/hybridnets.pth --source demo/video --output demo_result

I get the output: 

DETECTED SEGMENTATION MODE FROM WEIGHT AND PROJECT FILE: multiclass
video: demo/video/1.mp4
frame: 0
second: 1.33514404296875e-05
fps: 0.0

With no results in demo_result

**Comment by amita-kapoor** [comment]
Make sure you have the directory `demo_result` exists. Also, the source should be `demo/videp_1.mp4`.
