### ISSUE TITLE
training object detection

### ISSUE THREAD

**Issue by MIYU8305** [datvuthanh/HybridNets#80]
I have trained 
obj_list: ['car', 'person', 'rider', 'motor', 'bike'] thes class for object detection.

Done over than 200 epoch and 
used need_autoanchor: true and changed 
anchors_scales: '[1, 1.64, 1.71]'
anchors_ratios: '[(1.0, 1.0), (0.57, 1.84), (1.84, 0.57)]'
manually.

I got this performance as below.

![image](https://user-images.githubusercontent.com/63732178/218593182-bfa958a8-096c-418b-a370-d583150bd4b7.png)

I want to improve mAP, Could you give me a tip or teach me where need to check?

**Comment by datvuthanh** [comment]
Hi,

You can follow this steps:
1. Train with freeze segmentation head (200 epoch)
2. Freeze Backbone, Neck, Detection and train only segmentation head (50 epoch)
3. Train end2end (100 epoch)
4. Freeze backbone, neck (multi scale features) and train specify heads. (50 epoch)
5. Train end2end again (100 epoch)

Thank you.

**Comment by happyday-lkj** [comment]
> I have trained obj_list: ['car', 'person', 'rider', 'motor', 'bike'] thes class for object detection.
> 
> Done over than 200 epoch and used need_autoanchor: true and changed anchors_scales: '[1, 1.64, 1.71]' anchors_ratios: '[(1.0, 1.0), (0.57, 1.84), (1.84, 0.57)]' manually.
> 
> I got this performance as below.
> 
> ![image](https://user-images.githubusercontent.com/63732178/218593182-bfa958a8-096c-418b-a370-d583150bd4b7.png)
> 
> I want to improve mAP, Could you give me a tip or teach me where need to check?

did you train the model use single GPU or multi-gpu?
