### ISSUE TITLE
train with DDP 

### ISSUE THREAD

**Issue by happyday-lkj** [datvuthanh/HybridNets#90]
Hi,
   I try train the model with DDP model, with script `python train_ddp.py --num_gpus 2`
   however, I meet the error 
   `File "HybridNets/hybridnets/loss.py", line 500, in soft_tversky_score
    assert output.size() == target.size()
AssertionError
`
Then, I modidy the code class ModelWithLoss  in train_ddp.py with the “multilabel” instead of `model.seg_mode`, but the code seems  stopped .

**Comment by happyday-lkj** [comment]
![image](https://github.com/datvuthanh/HybridNets/assets/18274241/71fb1c92-0859-4254-a2ed-0387116fb89d)

when --num_gpus set to 1, the program work well, but when the gpu_nums set greater than 1, then the program seems stuck.

**Comment by happyday-lkj** [comment]
solved

**Comment by wanyunfeiAlex** [comment]
@happyday-lkj  hey, I've encountered the same problem. How did you fix that?

**Comment by happyday-lkj** [comment]
> @happyday-lkj hey, I've encountered the same problem. How did you fix that?

first, you can modidy the code class ModelWithLoss in train_ddp.py with the “multilabel” instead of model.seg_mode, then refactor the train_ddp.py follow this  [https://github.com/rentainhe/pytorch-distributed-training/tree/master](rep)

BTW, it also have some problems with val_ddp.py.

**Comment by wanyunfeiAlex** [comment]
> > @happyday-lkj hey, I've encountered the same problem. How did you fix that?
> 
> first, you can modidy the code class ModelWithLoss in train_ddp.py with the “multilabel” instead of model.seg_mode, then refactor the train_ddp.py follow this [https://github.com/rentainhe/pytorch-distributed-training/tree/master](rep)
> 
> BTW, it also have some problems with val_ddp.py.

thanks for your advice, I can train with DDP now.
