### ISSUE TITLE
I can't download the dataset file For BDD100K: imgs det_annot da_seg_annot ll_seg_annot. How do I get permission to download it?

### ISSUE THREAD

**Issue by txlan1710** [datvuthanh/HybridNets#97]

**Comment by holestine** [comment]
I have the same problem. I got access to BDD by registering at https://bdd-data.berkeley.edu/portal.html but the dataset links still don't work and it's unclear what I'm supposed to download. I tried a few things but they don't extract to anything like the recommended folder structure.

![image](https://github.com/datvuthanh/HybridNets/assets/2140017/b603cf2d-f523-4fee-bd63-6289ddbc6888)

**Comment by datvuthanh** [comment]
I updated the download links in README.md

**Comment by txlan1710** [comment]
@datvuthanh @holestine Thank you very so much
